### ISSUE TITLE
Video demo request

### ISSUE THREAD

**Issue by darothub** [gabrielaloho/GabrielAlohoDevPlacement2020#1]
Hi Dev,

Kudos to you. To aid the review could you add a link to a video demo of what you have done.

NB: The earlier the better

Thanks.

**Comment by ghost** [comment]
Thank you sir,
here is the link to the video
https://youtu.be/2lFPPM1-r1w

**Comment by darothub** [comment]
Hi Gabriel,

I asked for the demo of what you did not a tutorial.

By demo I meant a demonstration of the screen with user interactions.

And please kindly supply your name and email address.

**Comment by ghost** [comment]
Sorry about that Sir. Check this out here
https://youtu.be/JyvNTPVHqH0

**Comment by ghost** [comment]
Thank you for the feedback.
